### ISSUE TITLE
dipper SoterService force stopping.

### ISSUE THREAD

**Issue by OriginCode** [LineageOS/android_device_xiaomi_sdm845-common#2]

**Comment by YumeMichi** [comment]
Use MIUI 9.2.x vendor image or manually downgrade SoterService.apk. The existing org.ifaa.android.manager is not compatible with newer SoterService.apk.

**Comment by TheScarastic** [comment]
can anyone of you send logs for same?

**Comment by YumeMichi** [comment]
@TheScarastic Newer SoterService.apk requires a binder service called IFAAService, just like [this](https://github.com/GuaiYiHu/android_device_xiaomi_violet/commit/ce7fb49b813f5cecb391df9eecf0e17c6f289dd2).
